-- MySQL Script generated by MySQL Workbench
-- Sat May  3 23:31:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema plan_network
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `plan_network` ;

-- -----------------------------------------------------
-- Schema plan_network
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plan_network` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `plan_network` ;

-- -----------------------------------------------------
-- Table `plan_network`.`dev_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`dev_type` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`dev_type` (
  `id_dev_type` INT NOT NULL AUTO_INCREMENT,
  `dev_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dev_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`brand` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`brand` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NULL,
  PRIMARY KEY (`id_brand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`dev_model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`dev_model` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`dev_model` (
  `id_dev_model` INT NOT NULL AUTO_INCREMENT,
  `fbrand` INT NULL,
  `dev_type` INT NULL,
  `dev_model` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dev_model`),
  INDEX `fk_dev_model_brand_idx` (`fbrand` ASC) VISIBLE,
  INDEX `fk_dev_model_dev_type_idx` (`dev_type` ASC) VISIBLE,
  CONSTRAINT `fk_dev_model_brand`
    FOREIGN KEY (`fbrand`)
    REFERENCES `plan_network`.`brand` (`id_brand`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dev_model_dev_type`
    FOREIGN KEY (`dev_type`)
    REFERENCES `plan_network`.`dev_type` (`id_dev_type`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`edifice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`edifice` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`edifice` (
  `id_edifice` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  PRIMARY KEY (`id_edifice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`office_loc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`office_loc` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`office_loc` (
  `id_office_loc` INT NOT NULL AUTO_INCREMENT,
  `edifice` INT NULL,
  `wing` VARCHAR(45) NULL,
  `floor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_office_loc`),
  INDEX `fk_office_loc_edifice_idx` (`edifice` ASC) VISIBLE,
  CONSTRAINT `fk_office_loc_edifice`
    FOREIGN KEY (`edifice`)
    REFERENCES `plan_network`.`edifice` (`id_edifice`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`office` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`office` (
  `id_office` INT NOT NULL AUTO_INCREMENT,
  `office` VARCHAR(45) NULL,
  `office_edfice_location` INT NULL,
  PRIMARY KEY (`id_office`),
  INDEX `fk_office_office_loc_idx` (`office_edfice_location` ASC) VISIBLE,
  CONSTRAINT `fk_office_office_loc`
    FOREIGN KEY (`office_edfice_location`)
    REFERENCES `plan_network`.`office_loc` (`id_office_loc`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`rack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`rack` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`rack` (
  `id_rack` INT NOT NULL AUTO_INCREMENT,
  `office` INT NULL,
  `rack_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rack`),
  INDEX `fk_rack_office_idx` (`office` ASC) VISIBLE,
  CONSTRAINT `fk_rack_office`
    FOREIGN KEY (`office`)
    REFERENCES `plan_network`.`office` (`id_office`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`patchera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`patchera` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`patchera` (
  `id_patchera` INT NOT NULL AUTO_INCREMENT,
  `patchera` VARCHAR(45) NULL,
  `rack` INT NULL,
  PRIMARY KEY (`id_patchera`),
  INDEX `fk_patchera_rack_idx` (`rack` ASC) VISIBLE,
  CONSTRAINT `fk_patchera_rack`
    FOREIGN KEY (`rack`)
    REFERENCES `plan_network`.`rack` (`id_rack`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`switch_model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`switch_model` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`switch_model` (
  `id_switch_model` INT NOT NULL AUTO_INCREMENT,
  `switch_brand` INT NULL,
  `switch_model` VARCHAR(45) NULL,
  PRIMARY KEY (`id_switch_model`),
  INDEX `fk_switfch_model_brand_idx` (`switch_brand` ASC) VISIBLE,
  CONSTRAINT `fk_switfch_model_brand`
    FOREIGN KEY (`switch_brand`)
    REFERENCES `plan_network`.`brand` (`id_brand`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`switch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`switch` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`switch` (
  `id_switch` INT NOT NULL AUTO_INCREMENT,
  `switch_model` INT NULL,
  `serial_number` VARCHAR(45) NULL,
  `ports_q` VARCHAR(45) NULL,
  `rack` INT NULL,
  `office` INT NULL,
  `switch_port_in` INT NULL,
  `wall_port_in` INT NULL,
  `patch_port_in` INT NULL,
  PRIMARY KEY (`id_switch`),
  INDEX `fk_switch_switch_model_idx` (`switch_model` ASC) VISIBLE,
  INDEX `fk_switch_rack_idx` (`rack` ASC) VISIBLE,
  INDEX `fk_switch_office_idx` (`office` ASC) VISIBLE,
  INDEX `fk_switch_switch_port_in_idx` (`switch_port_in` ASC) VISIBLE,
  INDEX `fk_switch_wall_port_in_idx` (`wall_port_in` ASC) VISIBLE,
  INDEX `fk_switch_patch_port_in_idx` (`patch_port_in` ASC) VISIBLE,
  CONSTRAINT `fk_switch_switch_model`
    FOREIGN KEY (`switch_model`)
    REFERENCES `plan_network`.`switch_model` (`id_switch_model`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_switch_rack`
    FOREIGN KEY (`rack`)
    REFERENCES `plan_network`.`rack` (`id_rack`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_switch_office`
    FOREIGN KEY (`office`)
    REFERENCES `plan_network`.`office` (`id_office`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_switch_switch_port_in`
    FOREIGN KEY (`switch_port_in`)
    REFERENCES `plan_network`.`switch_port` (`id_switch_port`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_switch_wall_port_in`
    FOREIGN KEY (`wall_port_in`)
    REFERENCES `plan_network`.`wall_port` (`id_wall_port`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_switch_patch_port_in`
    FOREIGN KEY (`patch_port_in`)
    REFERENCES `plan_network`.`patch_port` (`id_patch_port`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`switch_port`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`switch_port` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`switch_port` (
  `id_switch_port` INT NOT NULL AUTO_INCREMENT,
  `switch` INT NULL,
  `port_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id_switch_port`),
  INDEX `fk_switch_port_switch_idx` (`switch` ASC) VISIBLE,
  CONSTRAINT `fk_switch_port_switch`
    FOREIGN KEY (`switch`)
    REFERENCES `plan_network`.`switch` (`id_switch`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`patch_port`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`patch_port` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`patch_port` (
  `id_patch_port` INT NOT NULL AUTO_INCREMENT,
  `patchera` INT NULL,
  `patch_port` VARCHAR(45) NULL,
  `switch_port_in` INT NULL,
  PRIMARY KEY (`id_patch_port`),
  INDEX `fk_patch_port_patchera_idx` (`patchera` ASC) VISIBLE,
  INDEX `fk_patch_port_switch_port_idx` (`switch_port_in` ASC) VISIBLE,
  CONSTRAINT `fk_patch_port_patchera`
    FOREIGN KEY (`patchera`)
    REFERENCES `plan_network`.`patchera` (`id_patchera`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patch_port_switch_port`
    FOREIGN KEY (`switch_port_in`)
    REFERENCES `plan_network`.`switch_port` (`id_switch_port`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`wall_port`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`wall_port` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`wall_port` (
  `id_wall_port` INT NOT NULL AUTO_INCREMENT,
  `wall_port_name` VARCHAR(45) NULL,
  `office` INT NULL,
  `patch_port_in` INT NULL,
  `switch_port_in` INT NULL,
  PRIMARY KEY (`id_wall_port`),
  INDEX `fk_wall_port_office_idx` (`office` ASC) VISIBLE,
  INDEX `fk_wall_port_patch_port_in_idx` (`patch_port_in` ASC) VISIBLE,
  INDEX `fk_wall_port_switch_port_in_idx` (`switch_port_in` ASC) VISIBLE,
  CONSTRAINT `fk_wall_port_office`
    FOREIGN KEY (`office`)
    REFERENCES `plan_network`.`office` (`id_office`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wall_port_patch_port_in`
    FOREIGN KEY (`patch_port_in`)
    REFERENCES `plan_network`.`patch_port` (`id_patch_port`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wall_port_switch_port_in`
    FOREIGN KEY (`switch_port_in`)
    REFERENCES `plan_network`.`switch_port` (`id_switch_port`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plan_network`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_network`.`device` ;

CREATE TABLE IF NOT EXISTS `plan_network`.`device` (
  `id_device` INT NOT NULL AUTO_INCREMENT,
  `dev_model` INT NULL,
  `device` VARCHAR(45) NULL,
  `wall_port_in` INT NULL,
  `switch_port_in` INT NULL,
  `patch_port_in` INT NULL,
  `serial_number` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  `office` INT NULL,
  PRIMARY KEY (`id_device`),
  INDEX `fk_device_dev_model_idx` (`dev_model` ASC) VISIBLE,
  INDEX `fk_device_wall_port_idx` (`wall_port_in` ASC) VISIBLE,
  INDEX `fk_device_switch_port_idx` (`switch_port_in` ASC) VISIBLE,
  INDEX `fk_patch_port_idx` (`patch_port_in` ASC) VISIBLE,
  INDEX `fk_device_office_idx` (`office` ASC) VISIBLE,
  CONSTRAINT `fk_device_dev_model`
    FOREIGN KEY (`dev_model`)
    REFERENCES `plan_network`.`dev_model` (`id_dev_model`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_device_wall_port`
    FOREIGN KEY (`wall_port_in`)
    REFERENCES `plan_network`.`wall_port` (`id_wall_port`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_device_switch_port`
    FOREIGN KEY (`switch_port_in`)
    REFERENCES `plan_network`.`switch_port` (`id_switch_port`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_device_patch_port`
    FOREIGN KEY (`patch_port_in`)
    REFERENCES `plan_network`.`patch_port` (`id_patch_port`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_device_office`
    FOREIGN KEY (`office`)
    REFERENCES `plan_network`.`office` (`id_office`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
